[my_servers]
node1 ansible_host=192.168.56.103 ansible_user=rus ansible_ssh_privat_key_file=/mnt/c/Users/rusii/.ssh/id_ed25519
node2 ansible_host=192.168.56.105 ansible_user=admin ansible_ssh_privat_key_file=/mnt/c/Users/rusii/.ssh/id_ed25519